version: '3.9'

services:
  postgres:
    image: postgres:15
    container_name: postgres-booking-app
    restart: always
    environment:
      POSTGRES_DB: bookingApp
      POSTGRES_USER: frasoprano
      POSTGRES_PASSWORD: frasoprano
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  keycloak:
    image: quay.io/keycloak/keycloak:22.0.1
    container_name: keycloak-booking-app
    restart: always
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: postgres
      KC_DB_URL_PORT: 5432
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: frasoprano
      KC_DB_PASSWORD: frasoprano
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - postgres

volumes:
  postgres_data: